Импорт библиотек

In [2]:
import numpy as np, sys
np.random.seed(1)

Импорт данных

In [3]:
from keras.datasets import mnist

In [6]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Обработка данных

In [16]:
images, labels = (X_train[0:1000].reshape(len(X_test), 28*28)/255,
                  y_train[0:1000])

In [ ]:
one_hot_labels = np.zeros((len(labels), 10))
for i,l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = X_test.reshape(len(X_test), 28*28)/255
test_labels = np.zeros((len(y_test), 10))
for i,l in enumerate(y_test):
    test_labels[i][l] = 1

In [ ]:
def tanh(x):
    return np.tanh(x)

def tanh2deriv(output):
    return 1 - (output**2)

def sortmax(x):
    temp = np.exp(x)
    return temp / np.sum(temp, axis=1, keepdims=True)

In [28]:
alpha, interations = (2, 300)
pixels_per_image, num_labels = (784, 10)
batch_size = 128

In [29]:
input_rows = 28
input_cols = 28

kernel_rows = 3
kernel_cols = 3
num_kernels = 16

In [ ]:
hidden_size = ((input_rows - kernel_rows)*
               (input_cols - kernel_cols))*nums_kernels

kernels = 0.02 * np.random.random((kernel_rows*kernel_cols, 
                                   num_kernels))-0.1

In [ ]:
def get_image_section(layer, row_from, row_to, col_from, col_to):
    section = layer[:, row_from:row_to, col_from:col_to]
    return section.reshape(-1, 1, row_to-row_from, col_to-col_from)

In [ ]:
for j in range(iterations):
    correct_cnt = 0
    for i in range(int(len(images) / batch_size)):
        batch_start, batch_end = ((i*batch_size), ((i+1)*batch_size))
        layer_0 = images[batch_start:batch_end]
        layer_0 = images.reshape(layer_0.shape[0], 28, 28)
        
        sects = list()
        for row_start in range(layer_0.shape[1] - kernel_rows):
            for col_start in range(layer_0.shape[2] - kernel_cols):
                sect = get_image_section(layer_0,
                                        row_start,
                                        row_start+kernel_rows,
                                         col_start,
                                         col_start+kernel_cols)
                sect.append(sect)
        expend_input = np.concatenate(sects, axis=1)
        es = expanded_input.shape
        flattened_input = expanded_input.reshape(es[0]*es[1], -1)
        
        kernel_output = flattened_input.dot(kernels)
        layers_1 = tanh(kernel_output.reshape(es[0], -1))
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask*2
        layer_2 = softmax(np.dot(layer_1, weights_1_2))
        
        for k in range(batch_size):
            labelset = labels[batch_start+k:batch_start+k+1]
            _inc = int(np.argmax(layer_2[k:k+1]) == 
                       np.argmax(labelset))
            correct_cnt += _inc
            
        layer_2_delte = (labels[batch_start:batch_end] - layer_2)/
        (batch_size*layer_2.shape[0])

In [67]:
np.random.randint(2, size = 10)

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 1])

In [47]:
d = np.concatenate(c, axis=1)
d

array([[[1, 2],
        [4, 5],
        [5, 6],
        [8, 9]]])

In [50]:
d.reshape(4, -1)

array([[1, 2],
       [4, 5],
       [5, 6],
       [8, 9]])

In [48]:
d.shape

(1, 4, 2)

In [56]:
a = np.array([[[1, 2, 3],
      [4, 5, 6]],
     [[5, 6, 7],
     [8, 9, 10]]])
b = list()
c = a[:,0:2, 0:2].reshape(-1, 1, 2, 2)
b.append(c)
c = a[:,0:2, 1:3].reshape(-1, 1, 2, 2)
b.append(c)
b

[array([[[[1, 2],
          [4, 5]]],
 
 
        [[[5, 6],
          [8, 9]]]]),
 array([[[[ 2,  3],
          [ 5,  6]]],
 
 
        [[[ 6,  7],
          [ 9, 10]]]])]

In [64]:
d = np.concatenate(b, axis=1)
g = d.shape
l = d.reshape(g[0]*g[1], -1)
l

array([[ 1,  2,  4,  5],
       [ 2,  3,  5,  6],
       [ 5,  6,  8,  9],
       [ 6,  7,  9, 10]])

In [65]:
l.reshape(g[0], -1)

array([[ 1,  2,  4,  5,  2,  3,  5,  6],
       [ 5,  6,  8,  9,  6,  7,  9, 10]])

In [53]:
array([[[[ 1,  2],
         [ 4,  5]],

        [[ 2,  3],
         [ 5,  6]]],


       [[[ 5,  6],
         [ 8,  9]],

        [[ 6,  7],
         [ 9, 10]]]])

AttributeError: 'list' object has no attribute 'reshape'

In [63]:
a = np.array([[[1, 2],
               [4, 5]],
             [[5, 6],
              [8, 9]]])
np.concatenate(a, axis=1)

array([[1, 2, 5, 6],
       [4, 5, 8, 9]])

In [ ]:
array([[[[1, 2],
         [4, 5]]],


       [[[5, 6],
         [8, 9]]]])

In [78]:
import pandas as pd
a = pd.DataFrame([['A', 2, 5, 6],
                 ['A', 5, 8, 9],
                 ['B', 5, 8, 9]])
a.groupby(0).agg('sum')

1   2   3
0           
A  7  13  15
B  5   8   9

In [75]:
a

0  1  2  3
0  A  2  5  6
1  A  5  8  9
2  B  5  8  9